# Generated by Django 5.2.11 on 2026-02-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrollnews',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
