# Generated by Django 5.2.11 on 2026-02-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_popularpost_category_popularpost_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_post', to='blog.category'),
        ),
    ]
