# Generated by Django 5.2.11 on 2026-02-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_popularpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('image', models.ImageField(upload_to='AboutPage')),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=130)),
                ('description', models.TextField(max_length=500)),
                ('url', models.URLField()),
            ],
        ),
    ]
