# Generated by Django 5.2.11 on 2026-02-05 16:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_popularpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularpost',
            name='category',
            field=models.TextField(default='general', verbose_name=blog.models.Category),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularpost',
            name='title',
            field=models.TextField(default=1, max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(max_length=130),
        ),
    ]
