# Generated by Django 5.2.11 on 2026-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
