# Generated by Django 5.2.12 on 2026-05-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='scrollnews',
            name='slug',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
