# Generated by Django 6.0.2 on 2026-03-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prduct',
            new_name='Product',
        ),
    ]
